import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ["400", "600", "700"],
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: {
    default: "Rahat Hossain",
    template: "%s | Rahat Hossain"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${poppins.className}`}
      >
        <NavBar />
        <main className="h-screen h-max-[600px] place-items-center place-content-center">
          {children}
        </main>
        <footer className="text-center bg-slate-600">Awesome next js project</footer>
      </body>
    </html>
  );
}
